services:
  - type: web
    name: mattermost
    runtime: image
    image:
      url: docker.io/mattermost/mattermost-team-edition:release-10.5
    plan: free
    autoDeploy: true
    healthCheckPath: /api/v4/system/ping

    envVars:
      # URL pública (ajústala tras el 1er deploy)
      - key: MM_SERVICESETTINGS_SITEURL
        value: "https://TU-URL.onrender.com"

      # DB Postgres gestionada por Render (plan Free)
      - key: MM_SQLSETTINGS_DRIVERNAME
        value: postgres
      - key: MM_SQLSETTINGS_DATASOURCE
        fromDatabase:
          name: mattermost-db
          property: connectionString

      # Logging útil
      - key: MM_LOGSETTINGS_CONSOLELEVEL
        value: "INFO"

    # En runtime:image no uses startCommand; usa dockerCommand si necesitas algo previo
    dockerCommand: >
      /bin/sh -lc 'chown -R 2000:2000 /mattermost || true; exec /entrypoint.sh mattermost'

databases:
  - name: mattermost-db
    databaseName: mattermost
    plan: free

