services:
  - type: web
    name: mattermost-pemser
    runtime: image
    image:
      url: docker.io/mattermost/mattermost-team-edition:release-10.12
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/v4/system/ping
    envVars:
      - key: MM_SERVICESETTINGS_SITEURL
        value: https://mattermost-pemser.onrender.com
      - key: MM_SQLSETTINGS_DRIVERNAME
        value: postgres
      - key: MM_SQLSETTINGS_DATASOURCE
        fromDatabase:
          name: mattermost-db
          property: connectionString
      - key: MM_CONFIG
        fromDatabase:
          name: mattermost-db
          property: connectionString
      - key: MM_PLUGINSETTINGS_ENABLE
        value: "true"
      - key: MM_PLUGINSETTINGS_ENABLEUPLOADS
        value: "true"
      - key: MM_LOGSETTINGS_CONSOLELEVEL
        value: INFO

databases:
  - name: mattermost-db
    databaseName: mattermost
    plan: basic-256mb
    diskSizeGB: 15
