services:
  - type: web
    name: mattermost-pemser
    runtime: image
    image:
      url: docker.io/mattermost/mattermost-team-edition:release-10.12
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/v4/system/ping

    # Disco persistente: TODO lo binario vive aquí
    disk:
      name: mm-data
      mountPath: /mattermost/data
      sizeGB: 10   # ajusta según lo que esperes almacenar

    envVars:
      # URL pública exacta (ajústala a la que Render te asigne)
      - key: MM_SERVICESETTINGS_SITEURL
        value: https://mattermost-pemser.onrender.com

      # Base de datos (datos de usuarios, posts, etc.)
      - key: MM_SQLSETTINGS_DRIVERNAME
        value: postgres
      - key: MM_SQLSETTINGS_DATASOURCE
        fromDatabase:
          name: mattermost-db
          property: connectionString

      # Guardar la configuración en la DB (System Console persiste)
        - key: MM_CONFIG
          value: postgresql://mattermost_ct0k_user:30MSBJXWxEAppJG9wQyoUvCnRh9UD9uj@dpg-d2vib6v5r7bs73ct2a60-a/mattermost_ct0k


      # ---- Archivos y Plugins en el DISCO local persistente ----
      # Todos los adjuntos/derivados van al disco montado
      - key: MM_FILESETTINGS_DIRECTORY
        value: /mattermost/data
      # Tamaño máx de archivo (20 MB ejemplo)
      - key: MM_FILESETTINGS_MAXFILESIZE
        value: "20971520"

      # Habilitar plugins y permitir subirlos desde la consola
      - key: MM_PLUGINSETTINGS_ENABLE
        value: "true"
      - key: MM_PLUGINSETTINGS_ENABLEUPLOADS
        value: "true"
      # Marketplace (opcional)
      - key: MM_PLUGINSETTINGS_ENABLEMARKETPLACE
        value: "true"
      - key: MM_PLUGINSETTINGS_ENABLEREMOTEMARKETPLACE
        value: "true"

      # Redirigimos las carpetas de plugins para que queden en el DISCO
      - key: MM_PLUGINSETTINGS_DIRECTORY
        value: /mattermost/data/plugins
      - key: MM_PLUGINSETTINGS_CLIENTDIRECTORY
        value: /mattermost/data/client/plugins

      # Logging útil en consola
      - key: MM_LOGSETTINGS_CONSOLELEVEL
        value: INFO

databases:
  - name: mattermost-db
    databaseName: mattermost
    plan: basic-256mb
    diskSizeGB: 15

