services:
  - type: web
    name: mattermost-pemser
    runtime: image
    image:
      url: docker.io/mattermost/mattermost-team-edition:release-10.12
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/v4/system/ping
    # numInstances: 2   # <-- opcional para mayor disponibilidad

    disk:
      name: mm-data
      mountPath: /mattermost/data
      sizeGB: 10

    envVars:
      - key: MM_SERVICESETTINGS_SITEURL
        value: https://mattermost-pemser.onrender.com
      - key: MM_SQLSETTINGS_DRIVERNAME
        value: postgres
      - key: MM_SQLSETTINGS_DATASOURCE
        fromDatabase:
          name: mattermost-db
          property: connectionString
      - key: MM_LOGSETTINGS_CONSOLELEVEL
        value: INFO

      # --- Plugins habilitados y persistentes en el disco ---
      - key: MM_PLUGINSETTINGS_ENABLE
        value: "true"
      - key: MM_PLUGINSETTINGS_ENABLEUPLOADS
        value: "true"
      - key: MM_PLUGINSETTINGS_DIRECTORY
        value: /mattermost/data/plugins
      - key: MM_PLUGINSETTINGS_CLIENTDIRECTORY
        value: /mattermost/data/client/plugins

      # (Opcional) límite de tamaño de archivos
      - key: MM_FILESETTINGS_MAXFILESIZE
        value: "20971520"

databases:
  - name: mattermost-db
    databaseName: mattermost
    plan: basic-256mb
    diskSizeGB: 15
